drone-plugins/drone-docker

DOCS.md
main.go

This PR adds support to the Docker plugin for saving/restoring Docker image layers to/from an archive file. Combined with the cache plugin it enables caching of image layers between builds.
Adds a new parameter:
Create a tarred repository containing all layers of the Docker image and restore the image repository on consecutive builds.
The `archive` value must be a dictionary defined with a required `file` and an optional `tag` key.
`file` can either be an absolute path starting with `/drone` or a relative path which will be expanded from the working directory.
`tag` allows limiting the export of the image layers to the supplied tag(s).
```yaml
archive:
file: docker/image.tar
tag: latest
```
```yaml
publish:
docker:
username: kevinbacon
password: $$DOCKER_PASSWORD
email: …
```

Add support for saving/restoring image layers from archive

---

DOCS.md
main.go

This is a follow up to PR #13 allowing the user to `load` and `save` image layers from/to separate files.
```yaml
load: docker/image.tar
save:
file: docker/image.tar
tags: latest
```
@bradrydzewski

Separate 'archive' parameter in 'load' and 'save'

---

DOCS.md
main.go

It is now possibile to optionally specify a mirror registry instead of pulling images directly from the central Hub.

Adding support to registry mirroring

---

main.go

Running `docker -d` is deprecated since [1].
[1]: https://docs.docker.com/engine/misc/deprecated/#old-command-line-options

Change deprecated argument -d -> daemon

---

DOCS.md
main.go

supersedes #25 (just rebased on `develop` branch)

Docker graph caching

---

Dockerfile

@tboerger @bradrydzewski 
The goal of this PR is to update the base image docker version from `1.9.1` to `1.10.2`. Motivation for this comes from consistently seeing the following error in drone builds:
```no-highlight
time="2016-03-08T20:46:42.180274293Z" level=warning msg="signal: killed" 
time="2016-03-08T20:46:42.226610787Z" level=warning msg="failed to cleanup ipc mounts:\nfailed to umount /var/lib/docker/containers/516bb2880e7b115e3957cdde1eef7f1075691527685c831dfb848b705e726c5d/shm: invalid argument\nfailed to umount /var/lib/docker/containers/516bb2880e7b115e3957cdde1eef7f1075691527685c831dfb848b705e726c5d/mqueue: invalid argument" 
[8] System error: mkdir /sys/fs/docker-daemon: read-only file system
[info] build failed (exit code 1)
```
A documented issue similar to the one above …

upgraded docker version

---

plugin.go

It should prepend `p.Login.Registry` only if login.registry is not equal to defaultRegistry and build.repo is not started with login.registry.

fixed appending registry before the repo

---

.drone.yml
Dockerfile
main.go
plugin.go

Docker 1.13.0 introduce some pretty good change we could support

[WIP] Docker 1.13

---

README.md

Since the other link doesn't exist.

Updated documentation link

---

plugin.go

`docker daemon` is deprecated is 1.13, we should use new binary instead: `dockerd` (see https://github.com/docker/docker/pull/26834)

Use dockerd instead of docker daemon

---

.gitignore
main.go
plugin.go

This fixes the last comment in issue https://github.com/drone-plugins/drone-docker/issues/34 - and adds a flag to allow _not_ pulling the base image down on every build.
I'm not 100% sure that the name I've given to the option is good, but I couldn't get the EnvVar options to work with a bool flag that was true-by-default correctly :/. This being my first go code ever, I'm happy to take any suggestions/help regarding this!
example usage:
```
publish:
image: plugins/drone-docker:<NEW_VERSION>
repo: <MY_REPO>
use_cache: true
volumes:
- /var/run/docker.sock:/var/run/docker.sock
```
Needs to be run as trusted for the volume obviously!

allowing docker to use cached base image in build

---

main.go

When using the config values `registry`, `username`, `password`, and `email`, if the corresponding `DOCKER_` env var is set, the explicit values are ignored. This is due to the `urfave/cli` package taking the first available env var.
This PR changes the order so that explicit configuration is favored over environmental. If the config order is intentional, please feel free to close this PR!
Thanks in advance!

Change env precedence

---

.drone.yml
Dockerfile

Update to using docker 17.04 in support of #119 
Also trying to utilize read of tags from file (courteous of #121)
I split this into 2 commits.  Feel free to let me know if you don't like how I'm doing the dynamic tagging.  I can remove/rework it.

Use Docker 17.04

---

plugin.go

This PR will untag the "temp" tag (`p.Build.Name`) from the image so that `docker system prune` can properly clean it up.  Currently `docker system prune` does nothing.
However, this PR will not work until Docker 17.04 is released as there is a bug prior to that where `docker system prune` does not properly clean dangling images.  https://github.com/docker/docker/issues/32006
So I just wanted to get this code/issue in the open.  We can either merge knowing it won't really do anything until 17.04 is released and the plugin uses it ... or wait until 17.04 is released and the plugin is using it before merging.

Remove temp tag from build and prune afterwards

---

main.go

DNS is a reserved keywork so the dns property is no longer being
converted into the PLUGIN_DNS environment variable. Changing the
name to custom_dns so the PLUGIN_CUSTOM_DNS env var will be passed
in.

Fix DNS passing. New env var is PLUGIN_CUSTOM_DNS

---

cmd/drone-docker-gcr/main.go

GOOGLE_APPLICATION_CREDENTIALS "should point to a file that defines the credentials", and should not be the contents of the credentials to follow Google's convention.
See https://developers.google.com/identity/protocols/application-default-credentials#howtheywork.
I replaced it with `TOKEN` to match the parameter of the previous GCR plugin worked, which may help with migrations.

Change possible password fields for GCR

---

cmd/drone-docker-ecr/main.go

Currently you have to specify static AWS credentials, this patch allow the sdk to use the instance- or container-role again.

Allow ecr login with default aws credential chain

---

.drone.yml
docker/Dockerfile

Uses the latest stable dind by default, which at the minute has better default ca certificates.

Use stable v17.12 Docker dind image.

---

.drone.yml
cmd/drone-docker-ecr/main.go
cmd/drone-docker-ecr/main_test.go

This addresses an issue when using `plugins/ecr` with `create_repository: true`. The current `TrimPrefix()` call tries to create a repo with a name like `/namespace/repo` which fails AWS API's [repositoryName constraints](https://docs.aws.amazon.com/AmazonECR/latest/APIReference/API_CreateRepository.html#ECR-CreateRepository-request-repositoryName).
I believe this might address some of the issues @mhumeSF mentioned in [here](https://discourse.drone.io/t/plugins-ecr-does-not-auto-create-repo-in-ecr/1099).

Fix ECR registry string trimming

---

cmd/drone-docker/main.go
docker.go

In order to use the multi-stage build we should specify the `--target` flag (official [docs](https://docs.docker.com/engine/reference/commandline/build/#specifying-target-build-stage-target)), this PR allow us to indicate the layer to build, eg:
```diff
pipeline:
publish-dev:
image: plugins/docker
repo: mavimo/test
tags: [ "latest", "prod" ]
+    target: production
when:
branch: master
event: push
publish-dev:
image: plugins/docker
repo: mavimo/test
tags: [ "latest", "dev" ]
+    target: development
when:
branch: develop
event: push
```
`Dockerfile`:
```
FROM php:7.1.13-fpm as production
COPY config/php.ini /usr/local/etc/php/php.ini
WORKDIR /srv
CMD ["php-fpm"]
FROM production as development
RUN apt-get update && apt-get install -y wget zip unzip git
```
NB: porting from …

Allow build for a specific target

---

cmd/drone-docker/main.go
docker.go

After the label-schema.org label support was added, this PR now adds the strongly suggested `org.label-schema.version` label by default and adds support for 'regular' labels similar to the tags and build args.
This incidently solves both comments in the original PR ;) 
For backwards compatibility I've kept the `label-schema` option.
#134 
#135

Add support for non label-schema labels

---

cmd/drone-docker/main.go

As in #201 mentioned it can be helpful to allow static tags in addition to the auto tags. I. e.: having a production tag that always matches the last tag.
closes #201

append tags with autotag instead of replacing

---

cmd/drone-docker/main.go

Reverts drone-plugins/drone-docker#245. @foosinn if you still would like to see that feature please make sure that auto tagging won't get broken as with this patch it always applies `latest`.

Revert "Reapply append tags with autotag instead of replacing"

---

cmd/drone-docker-ecr/main.go

Hey! This PR ensures that the ecr executable honors the user specified registry.
The current behavior uses the registry returned by the ECR authentication token regardless of what the user specifies. While this registry is a good default, the token also authenticates the client to push to any other repository that has an AWS trust relationship established with the current account. We should let the user specify one such registry.

Use the user specified Registry

---

cmd/drone-docker/main.go
daemon.go
daemon_win.go
docker.go

I've added the possibility to create a docker config for the root user from variable.
In this way using a secret you will be able to add all the authentication parameters for all the registries that you want.
In this example I need to authenticate to
-  registry.redhat.io (as build step)
- quey.io (as Dockerfile FROM as sourcedata)
- docker.io (as Dockerfile FROM as dockerexample)
- selfhosted_registry (as Dockerfile FROM as localdata)
example:
```yaml
kind: pipeline
name: default
image_pull_secrets:
- dockerconfig
steps:
- name: pull ubi7
image: registry.redhat.io/ubi7/ubi:7.7
purge: false
commands:
- echo $HOSTNAME
- name: pull ose-ansible
image: registry.redhat.io/openshift3/ose-ansible:latest
purge: false
commands:
- echo $HOSTNAME
- name: build and publish on internal registry
image: …
```

Added docker configuration

---

docker.go

We are trying to utilize image caching from the host machine a bit more and we're using the docker socket volume mount and seeing an issue with the `docker prune` such as the following:
pipeline is here : https://github.com/rancher/rancher/blob/master/.drone.yml#L345-L452
error: https://drone-publish.rancher.io/rancher/rancher/2828/3/4 pertinent parts below.
```
215 | + C:\bin\docker.exe rmi 2cd59a6e1694658e28b85deba6c9440f7496daf0
216 | Untagged: 2cd59a6e1694658e28b85deba6c9440f7496daf0:latest
217 | + C:\bin\docker.exe system prune -f
218 | Error response from daemon: a prune operation is already running
219 | exit status 1
```
This PR adds a similar check as the `isCommandPull` check so that we ignore the error and move on and assume the next job will successfully call `rmi` and …

Adding Ignore Checks for prune and rmi

---

docker.go
docker/docker/Dockerfile.linux.amd64
docker/docker/Dockerfile.linux.arm
docker/docker/Dockerfile.linux.arm64

As commented in #244 few changes as been made to docker dind. 
Per default, Docker daemon now listen on a UNIX AND TCP with TLS sockets, the client also tries to connect on the openned TCP socket (default behavior)
Since we don't need to expose Docker API with a TCP socket, I just started the daemon with UNIX socket and made the client trying to connect using UNIX socket like before.
I double checked docker entrypoint flow for this PR https://github.com/docker-library/docker/blob/master/19.03/dind/dockerd-entrypoint.sh#L129#L132 and since we start using `drone-docker` binary, almost all of this entrypoint code is useless
The only doubt I have is, I needed to run my test image `tuxity/drone-docker` with `privileged: true` in order to correctly start the docker daemon. I guess it's because …

Update Docker to 19.03.8

---

docker.go

forgot to bump the prune check +1 arg location per this error output
```
+ C:\bin\docker.exe rmi 6a7313a1c02bc1943a80305385b80bf1df1bce88
--
121 | Error: No such image: 6a7313a1c02bc1943a80305385b80bf1df1bce88
122 | Could not remove image 6a7313a1c02bc1943a80305385b80bf1df1bce88. Ignoring...
123 | + C:\bin\docker.exe system prune -f
124 | Error response from daemon: a prune operation is already running
125 | exit status 1
```

changed prune to 3rd arg in check

---

.drone.yml

The Windows docker builds should only be triggered when there's a push to master or a tag. Also add proper tagging to the Windows builds.

Fix Windows build

---

cmd/drone-ecr/main.go

Hello!
AWS has added support of automatic ECR images scanning for vulnerabilities last year(https://aws.amazon.com/about-aws/whats-new/2019/10/announcing-image-scanning-for-amazon-ecr/). This can be enabled during repo creation or for already existing repos.
I have a lot of ECR repos created by ecr-plugin via  **"create_repository: true"** setting. 
But I run into the problem when I wanted to enable image scanning on all this repos. As these repos were created/managed by ecr-plugin I think it would be mistake to manage scan setting for these repos with some other automation tool like terraform. Because this increase complexity and split management of ECR repos between two tools.
So I've added new setting **scan_on_push** which is false by default. When you have this setting set to …

ECR: adding setting to enable image scanning while repo creation

---

docker/docker/Dockerfile.linux.amd64
docker/docker/Dockerfile.linux.arm
docker/docker/Dockerfile.linux.arm64

Alpine 3.14 requires update seccomp profile

Update seccomp to 20.10 docker

---

cmd/drone-ecr/main.go

Greetings!
This change adds [external ID](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_create_for-user_externalid.html) support to `plugins/ecr`. With this change, our engineering teams will be able to use the instance role of our agents to push ECR images to their accounts more securely. 
I tested to ensure this doesn't break existing assume role functionality.

adding support for externalId

---

docker/docker/Dockerfile.linux.amd64
docker/docker/Dockerfile.linux.arm64

This is an alternative to #327. As the discussion on that PR shows, it
seems docker is not going to provide updates for the arm32 platform
anymore.
Fixes #326 and fixes #330.

Upgrade Docker dind to 20.10.9 for 64bit platforms

---

.drone.yml

Serialize windows 1809 pipelines since there is only 1 ssh runner present for 1809.

Serialize windows 1809 pipelines

---

card.go
docker.go
docs/card.data.json
docs/card.json
go.mod
go.sum

```json
{"Id":"sha256:77ccc7fcb43f52addf66f151b029d5e3a1875530c003e5e5326f4dd5f6f25bd3","RepoTags":["798a0dae10d63d281eff4c06eaa12001ffd23740:latest","tphoney/test:latest"],"ParsedRepoTags":[{"Tag":"tphoney/test:latest"}],"RepoDigests":["tphoney/test@sha256:c1d4f3fc280c1c9244537167923776f7c1e3b90c51e86e7d2bd8ee702e29202c"],"Parent":"sha256:850d0bad68362183f567cb66f726c8846e72b64f0dfba00068c71b8ed0ac8701","Comment":"","Created":"2022-02-23T12:09:54.2700425Z","Container":"3469ab8382992e0da6bec13419fc2338e7e2bcb07f45d7e7e5b721aa91de356d","DockerVersion":"20.10.9","Author":"","Architecture":"amd64","Os":"linux","Size":14046978,"VirtualSize":14046978,"Metadata":{"LastTagTime":"2022-02-23T12:09:54.3138666Z"},"SizeString":"13.40MB","VirtualSizeString":"13.40MB","Time":"2022-02-23T12:09:54Z","URL" …
```

(DRON-237) cards add link to image repo, minor cleanup

---

cmd/drone-docker/main.go
docker.go
docker_test.go

#356 introduced the possibility to use the Buildkit secrets feature when building the Docker image. However, it's not possible to specify more than one secret due to the fact that the setting is a simple string that gets used as value of the `--secret` CLI arg. I wasn't also happy with the fact that the `secret` setting was basically just the plain value of the arg, leading people to need the knowledge of the syntax of the `docker build` command to use it. For this reason, I splitted the setting into two: `secrets_from_env` and `secrets_from_file`. These new settings are just a list of strings in the format `key=value`, where the key is the name of the secret and the value can be the name of an environment variable or a file path. This PR also supersedes #332 somewhat.
- `Dockerfile`: …

Add support for multiple Buildkit secrets with env vars or files as source

---

card.go

Windows docker builds failed to create the card using `docker inspect` because docker isn't on the path. Instead use `dockerExec` from `daemon.go` which has the full path to the executable.

Use full path to docker when creating card

---

cmd/drone-docker/main.go
docker.go
docker_test.go

Add a --platform flag so that the user can specify a value for the corresponding flag passed to docker. This is useful in the context of multi-arch builds and buildkit (DOCKER_BUILDKIT=1 in the environment).
Signed-off-by: Marcelo E. Magallon <marcelo.magallon@grafana.com>

Add support for docker --platform flag

---

.gitignore
cmd/drone-docker/main.go
daemon.go
docker.go
docker_test.go

This allows adding of multiple ssh keys to a build, 
eg 
```yaml
kind: pipeline
type: docker
name: default
steps:
- name: docker
image: plugins/docker:latest
pull: never
environment:
settings:
dockerfile: Dockerfile
tags:
- silly
repo: tphoney/bash
ssh_agent_key: LS0tLS1CRUdJTiBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0KYjNCbGJuTnphQzFyWlhrdGRqRUFBQUFBQkc1dmJtVUFBQUFFYm05dVpRQUFBQUFBQUFBQkFBQUJGd0FBQUFkemMyZ3RjbgpOaEFBQUFBd0VBQVFBQUFRRUE0dVZJRTVJUjZmemY4Q1R5N3dVU2UrY25ZTUxHRWJrTEtENWRTYjRqc0ExODlmOE9YSUpzCmYzZHNqWkl4eVoyUHlTU3lLUkNtaHluYk8rajZaSjBPMnVaWWI2VU9EQW5VZGdtMlduUkZIL2xUYkJNN0RMSVh5bG5HYXUKVzVpZm1aVzllem1Sc09XN1JHU2hDSVprNmZZUHRWT1lhTE5WN3ArREZjZkRRcmxETWdMK1hkbWthS3NadTNTZXBYa1VQMwpuMHdPUkdlMExzTm9pcnpCQmcveWdDVTQ0SDBEdjhzUm1OVUZIWEVleWZwOTFRYjQ3UWdCOVVlbERlQXJwQ1BXVHZqMHBUCnJBQlJqU0hpVXpQ …
```

Add option to mount host ssh agent (--ssh)

---

card.go
cmd/drone-docker/main.go
docker.go
docker_test.go
go.mod
go.sum

Bug:
Created 2 dockerfiles where we set the below environment variables and built them in parallel:
`testimg:1.0` : `ENV GOPATH=$HOME/go`
`testimg2:2.0` : `ENV GOPATH=$HOME/go2`
Parallel Step 1:
Parallel Step 2:
Reproduced the bug where both testimg and testimg2 were the same (since the environment variable set was the same) after they were built. Ideally the should be different:
Commands used:
`testimg:1.0`:
`docker run --name=testcontainer1 rutvijspit/testimg:1.0`
`docker exec testcontainer1 sh -c /usr/bin/env | grep GOPATH`
`testimg2:2.0`:
`docker run --name=testcontainer2 rutvijspit/testimg2:2.0`
`docker exec testcontainer2 sh -c /usr/bin/env | grep GOPATH`
After the fix:
Parallel Step 1:
Parallel Step 2:
Verification that different environement variable is set:

fix: Use unique build name for build and tag

---

internal/docker/config.go

The docker string match check for registry while adding to config is removed to support other docker compliant registries too.

remove docker registry string match

---

docker.go

This upgrade includes changes in base buildx version:
Changed the login to docker login command instead of using the Config struct for OIDC changes.
Made the decision to use login instead of writing file directly.
Why the change was made - The login function integrates with various credential helpers, it also handles different registry specific logic in a better way, as opposed to config write where different registries need to be addressed differently.
It handles any changes in the authentication process across different Docker versions.
https://docs.google.com/document/d/153BXzvNWUZ-XD2qOIuPDQ3XWVSI89tR0uBppLNS-F-4/edit

Change docker login method, from config writing to login func

---

cmd/drone-ecr/main.go

New input `skip_push_if_tag_exists` flag to the Drone ECR plugin, allowing users to skip the image push if the specified tag already exists in the repository. The logic supports both mutable and immutable repositories, checking for existing tags before proceeding with the build and push.

feat: [CI-16181]: New input skip_push_if_tag_exists

---

COSIGN_USAGE.md
cmd/drone-docker/main.go
daemon.go
daemon_win.go
docker.go
docker/docker/Dockerfile.linux.amd64
docker/docker/Dockerfile.linux.arm64
docker/docker/Dockerfile.windows.amd64.1809
docker/docker/Dockerfile.windows.amd64.ltsc2022

Adds container image signing capability using Cosign directly within the drone-docker plugin. Now supports signing images using their immutable digests with proper fallback to tag-based signing.
New Inputs:
- PLUGIN_COSIGN_PRIVATE_KEY: Private key content (PEM) or file path
- PLUGIN_COSIGN_PASSWORD: Optional password for encrypted keys
- PLUGIN_COSIGN_PARAMS: Optional additional cosign parameters
Features:
- Signs using immutable digest references (repo@sha256:digest) for better security
- Falls back to tag-based signing if digest unavailable
- Non-interactive operation with COSIGN_YES=true
- Handles both embedded PEM keys and file paths
- Signs after push completes, ensuring registry digest is used
Testing:
https://github.com/user-attachments/assets/ea2383a3-0a53-4af3-8208-e34a128c9b9d

feat: [CI-18308]: Add Cosign Image Signing Support
