drone-plugins/drone-docker

main.go
now it's not work becaouse file != context
see more here https://docs.docker.com/reference/commandline/build/
after we can change docs ^)
=> fix(file): fixing work with Dockerfile.*

main.go
=> Fix `vars` typo

DOCS.md
=> Update DOCS to match the latest code

Dockerfile
update from rancher/docker:1.8.1 to 1.9.1
=> docker image update

DOCS.md
Obsoletes #24 because of inactivity.
=> Added grub known issue for Debian

Dockerfile, README.md, main.go, plugin.go
Tested on a 0.5 installation. Should be good to go.
Fixes #57
=> Use dind image

DOCS.md, main.go
added —mtu flag for docker daemon
=> add MTU settings to docker daemon

main.go
=> Fixed login to docker registry with empty email

plugin.go
This makes it so the plugin implicitly adds proxy values as build args. It is done implicitly as the proxy values are contained within the agent and the information might not be known to the person creating the build.
Currently it checks to see if the values were set as build args and it will ignore the agent's values.
Also it sets the upper and lower case versions of the proxy values as I've found that this needs to happen.
@bradrydzewski @tboerger @Bugagazavr
=> Adding proxy values to build args

main.go, plugin.go
Add support for compressing build context during image build (see https://github.com/docker/docker/pull/25837)
=> Support --compress docker build flag

plugin.go
Added ability for plugin to cleanup unused containers, volumes, images.
Useful when using caching plugins to reduce docker build times and keep the cache size in check.
Also seems like there were plans to implement this previously.  Became a lot easier with Docker 1.13. 😃
=> Remove unused docker data

main.go, vendor/github.com/urfave/cli/CHANGELOG.md, vendor/github.com/urfave/cli/README.md, vendor/github.com/urfave/cli/app.go, vendor/github.com/urfave/cli/command.go, vendor/github.com/urfave/cli/context.go, vendor/github.com/urfave/cli/errors.go, vendor/github.com/urfave/cli/flag.go, vendor/github.com/urfave/cli/flag_generated.go, vendor/github.com/urfave/cli/generate-flag-types, vendor/github.com/urfave/cli/help.go, vendor/github.com/urfave/cli/runtests, vendor/vendor.json
=> Allow reading tags from file

cmd/drone-docker/main.go
It looks like this was copypasta'd from daemon.debug
=> Fix daemon.off Usage string

.drone.yml, docker/Dockerfile
17.05.0 is not stable version and latest stable version 17.09 have some significant changes.
=> Change base image from 17.05.0-ce-dind to stable-dind

.drone.sh, cmd/drone-docker/main.go, docker.go
Allows for clean build using --no-cache. Resolves #165
=> Add no-cache option

docker/docker/Dockerfile.linux.amd64, docker/docker/Dockerfile.linux.arm, docker/docker/Dockerfile.linux.arm64, go.sum, tags.go, tags_test.go
cc @tboerger 
Signed-off-by: Bo-Yi Wu <appleboy.tw@gmail.com>
=> feat(version): support 18.06.0 tag format.

cmd/drone-ecr/main.go
This'll allow one to specify a json file in the repo that has a lifecycle or repository policy that'll be applied to the ECR repo.
=> Add ability to append lifecycle and repository policies for ECR

cmd/drone-docker/main.go
Reverts drone-plugins/drone-docker#242
=> Revert "append tags with autotag instead of replacing"

cmd/drone-docker/main.go, docker.go
Add the `add-host` flag for build
=> Add build add-host

go.mod, go.sum
https://discourse.drone.io/t/update-amazon-sdk-for-plugins-docker/6537
=> Update AWS SDK

.drone.yml, docker/docker/Dockerfile.windows.1909, docker/docker/manifest.tmpl
just copy pasta for 1909, not sure it will work but here we go.
=> adding windows 1909

cmd/drone-docker/main.go, docker.go
As title.
This adds the option for using the `--quiet` flag during builds.
=> Add quiet build option

docker/docker/Dockerfile.linux.amd64, docker/docker/Dockerfile.linux.arm, docker/docker/Dockerfile.linux.arm64
Reverts drone-plugins/drone-docker#322
=> Revert "Update seccomp to 20.10 docker"

docs/card.json
=> (fix) Update card.json with UX

.drone.yml, README.md, cmd/drone-gar/main.go, docker/gar/Dockerfile.linux.amd64, docker/gar/Dockerfile.linux.arm64, docker/gar/Dockerfile.windows.amd64.1809, docker/gar/Dockerfile.windows.amd64.ltsc2022, docker/gar/manifest.tmpl, internal/gcp/tokenutil.go
Based on feedback, splitting out gar/gcr
=>  ci-3011- split out gar/gcr

cmd/drone-ecr/main.go
=> Fixed 'error getting ECR auth: WebIdentityErr: unable to read file at…' issue
